export const localProducts = [
  {
    name: "Roti Sari Madu",
    description: "Roti mani lembut dengan kandungan serat tinggi",
    price: 25000,
    imageUrl: "/1.png",
    kategori: "roti-manis",
    status: "New",
  },
  {
    name: "Croissant Almond",
    description: "Croissant renyah dengan topping almond slice",
    price: 18000,
    imageUrl: "/2.png",
    kategori: "roti-manis",
    status: "New",
  },
  {
    name: "Donat Coklat",
    description: "Donat empuk dengan topping coklat dan meses warna-warni",
    price: 8000,
    imageUrl: "/3.png",
    kategori: "roti-manis",
    status: "Terlaris",
  },
  {
    name: "Bagel Blueberry",
    description: "Bagel lembut dengan isian selai blueberry asli",
    price: 15000,
    imageUrl: "/4.png",
    kategori: "roti-manis",
    status: "New",
  },
  {
    name: "Roti Coklat Almond",
    description: "Roti manis dengan isian coklat dan topping almond",
    price: 17000,
    imageUrl: "/5.png",
    kategori: "roti-manis",
    status: "Terlaris",
  },

  // Roti Isi
  {
    name: "Roti Coklat Keju",
    description: "Roti isi coklat dan keju dengan taburan meses",
    price: 12000,
    imageUrl: "/6.png",
    kategori: "roti-isi",
    status: "Terlaris",
  },
  {
    name: "Roti Ayam Pedas",
    description: "Roti isi ayam pedas gurih dengan bumbu khas",
    price: 15000,
    imageUrl: "/7.png",
    kategori: "roti-isi",
    status: "New",
  },
  {
    name: "Roti Sosis Mayo",
    description: "Roti isi sosis dengan saus mayo dan keju",
    price: 17000,
    imageUrl: "/8.png",
    kategori: "roti-isi",
    status: "New",
  },
  {
    name: "Roti Tuna Spesial",
    description: "Roti isi tuna dengan saus spesial dan sayuran segar",
    price: 20000,
    imageUrl: "/9.png",
    kategori: "roti-isi",
    status: "Terlaris",
  },
  {
    name: "Roti Telur Mayo",
    description: "Roti isi telur dan mayonaise creamy",
    price: 16000,
    imageUrl: "/10.png",
    kategori: "roti-isi",
    status: "New",
  },

  // Roti Kering
  {
    name: "Roti Kering Coklat",
    description: "Roti kering rasa coklat yang renyah dan manis",
    price: 10000,
    imageUrl: "/11.png",
    kategori: "roti-kering",
    status: "New",
  },
  {
    name: "Kastengel",
    description: "Kue kering dengan rasa keju gurih dan renyah",
    price: 35000,
    imageUrl: "/12.png",
    kategori: "roti-kering",
    status: "Terlaris",
  },
  {
    name: "Putri Salju",
    description: "Kue kering lembut dengan taburan gula halus",
    price: 30000,
    imageUrl: "/13.png",
    kategori: "roti-kering",
    status: "New",
  },
  {
    name: "Roti Kering Pandan",
    description: "Roti kering rasa pandan harum dan gurih",
    price: 15000,
    imageUrl: "/14.png",
    kategori: "roti-kering",
    status: "New",
  },
  {
    name: "Roti Kering Vanila",
    description: "Roti kering rasa vanila yang renyah",
    price: 15000,
    imageUrl: "/15.png",
    kategori: "roti-kering",
    status: "New",
  },

  // Roti Lainnya
  {
    name: "Roti Pisang Coklat",
    description: "Roti isi pisang dan coklat dengan topping wijen",
    price: 14000,
    imageUrl: "/16.png",
    kategori: "roti-lainnya",
    status: "New",
  },
  {
    name: "Roti Pizza Mini",
    description: "Roti pizza dengan topping sosis, keju, dan saus tomat",
    price: 16000,
    imageUrl: "/17.png",
    kategori: "roti-lainnya",
    status: "Terlaris",
  },
  {
    name: "Roti Tawar Gandum",
    description: "Roti tawar dengan bahan gandum utuh yang sehat",
    price: 20000,
    imageUrl: "/18.png",
    kategori: "roti-lainnya",
    status: "New",
  },
  {
    name: "Roti Lapis Strawberry",
    description: "Roti lapis dengan isian selai strawberry segar",
    price: 15000,
    imageUrl: "/19.png",
    kategori: "roti-lainnya",
    status: "New",
  },
  {
    name: "Roti Kentang Isi Ayam",
    description: "Roti kentang empuk dengan isian ayam cincang",
    price: 18000,
    imageUrl: "/20.png",
    kategori: "roti-lainnya",
    status: "Terlaris",
  },
];
